spring:
  data:
    mongodb:
      uri: mongodb://devuser:devpassword@localhost:27017/menuservice_db?authSource=admin

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s