server:
  port: 8081

spring:
  application:
    name: menu-service


management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # 100% sampling rate
    propagation:
      type: w3c


logging:
  level:
    root: info
#    io.opentelemetry: DEBUG
#    io.opentelemetry.exporter: DEBUG
#    io.opentelemetry.sdk.trace.export: DEBUG
#    io.opentelemetry.exporter.otlp: DEBUG

