server:
  port: 8081

spring:
    application:
        name: menu-service
    config:
        import: "optional:configserver:"
    cloud:
        consul:
            host: localhost
            port: 8500
            discovery:
                enabled: true
                register: true
                prefer-ip-address: true
                health-check-path: /actuator/health
                health-check-interval: 10s

management:
    endpoints:
        web:
            exposure:
                include: "*"

logging:
  level:
    root: info